- name: copy some files
  template:
    src: get-stuff.ps1
    dest: c:\terraform\get-stuff.ps1


- name: Install Chrome
  win_package:
    path: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B30936761-8AF3-D868-0730-0CA4EFD38929%7D%26lang%3Den%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Dempty/chrome/install/ChromeStandaloneSetup64.exe
    product_id: '{CF2BEAAA-26EA-32F8-AA9B-331F7E34BA97}'
    arguments:
    - /install
    - /passive
    - /norestart