- name: copy some files
  template:
    src: get-stuff.ps1
    dest: c:\terraform\get-stuff.ps1


- name: Get chrome installer
  win_get_url:
    url:  https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BD8039FB0-E1F9-DCC3-E3E8-C66CC0925792%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_0%26brand%3DGCEB/dl/chrome/install/GoogleChromeEnterpriseBundle64.zip
    dest: c:\users\colin\downloads

- name: unzip the installer
  win_unzip:
    src: c:\users\colin\downloads\GoogleChromeEnterpriseBundle64.zip
    dest: c:\temp\chrome

- name: install chrome
  win_package:
    path:  c:\temp\chrome\installers\GoogleChromeStandaloneEnterprise64.msi
    product_id: '{104B4CED-D037-33A4-B0A4-3995A7B733B9}'
    wait: yes
    state: present

- name: cleanup zip
  win_file:
    path: c:\users\colin\downloads\GoogleChromeEnterpriseBundle64.zip
    state: absent

- name: cleanup bundle
  win_file:
    path: c:\temp\chrome
    state: absent